language: node_js
before_install: npm install -g grunt-cli
node_js:
- '0.12'
- '0.10'
- iojs
after_success:
- npm run coveralls
deploy:
  provider: npm
  email: cwhenderson20@gmail.com
  api_key:
    secure: voU2ETsDdB7MaEmc47rqYbd66mdF4XLXGdP6uE/HRhz0o+qPKeiHvn9W6dvHiMcedzR8pFB6qa4Q3dhvmFk4vCM7ltN9vGVkr2E79b5iQ3JiaNtUGHMgRHm8+b859+IAV4Pl9iw5JHjll7cK4yAketPH2njltcz3OSa5AlQBqmM7e2HF9Bl014u2KMnnX4/7FPF2XpokXUeB0z214FS2/wMEBFOgBM2oGWylGVpOotq4G6hE1nM69OvA8x0bCx6cF1U2dau1qfeh5KadJhKTIHyOhztTLdWtsEoj+MfaQ8VmbX/a5AuWMCyZVrO847L1KMoZixq4nX1zVyWZxMkqyd/Abxs0iyMsL5ujPInbp2zpmbW5whWL9AJWotymfDpRfQ4ezSpIWiyUePBL9Oj7pJAHTfrVHvFaPgeemKhEZzhCQ3Z5tsk+5L0QGwHf3sFKsmoMNmrKLqFvGt8roii7Ns5S5jNEEVJAZmIKZB2mDghyDj3gcEBfRnonyUUykCb/8DjJwiQ75eIuEAHcgAJQj4EvuAGA+DprNVWZKqsw8OAIiJZB4L5oWV3G83oFYSeykNcTCrG9uxZcuaZTb3RxeopaRoHW7FQuGFBd1AO/e7TOPrQ+KU8VAu6jvXhN9ZPWeOs5dhT57IcrQqJfCkJ9Ht99rmGQRTvNa3TBH4snx54=
  on:
    tags: true
    repo: cwhenderson20/rollbar-api
